Back button bug
milaitinen/mobile-reporting-app-front pull request #48
Opened 2018-02-18 20:07 UTC by pedui

"Back buttonilla login screeniin ei kirjaa käyttäjää ulos"-bugin fiksailuja tehty. Does it work?

2018-02-18 20:32 UTC, 1krt approved these changes
Näyttäis toimivan oikein Androidilla.

2018-02-18 20:38 UTC, liikinn approved these changes
Näyttää toimivan hyvin 👍

2018-02-18 21:01 UTC, milaitinen requested changes
Melkein toimii iosilla (en ole testannut androidilla), mut jos palaa esim maisalla loginScreeniin back buttonilla ja painaa sign in (ilman että kirjoittaa mitään username&password kenttään), niin edelleen pääsee maisan tiedoilla TemplateScreeniin. En tiedä onko se tarkoituksenmukaista, mut sen voisi vielä ehkä korjata...? Muuten kaikki toimii hyvin :)

2018-02-18 21:05 UTC, pedui commented
Hyvä huomio! Sillain sen ei pitäis käyttäytyy. Koitan korjata 👍

2018-02-20 22:32 UTC, pedui commented
Nyt taitaa olla se bugi osittain fiksattu! Tarkastakaa vielä, että se ei teillä enää tee tota Minnan paljastamaa vekkulointia 🙏

2018-02-21 11:05 UTC, liikinn commented
Nyt näyttää toimivan oikein!

2018-02-21 11:33 UTC, kristertorikka commented
Näyttäis toimivan oikein ja bugi korjattu.

2018-02-21 12:57 UTC, milaitinen approved these changes

2018-02-22 10:47 UTC, merged